[package]
name = "rusty-yarn-spinner-compiler"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
antlr-rust = "0.3.0-beta"
better_any = "0.2.0"
rusty-yarn-spinner-core = { path = "../core" }
