[package]
name = "yarn_slinger_compiler"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = []
serde = ["dep:serde", "bevy?/serialize", "yarn_slinger_core/serde"]
bevy = ["dep:bevy", "yarn_slinger_core/bevy"]

[dependencies]
antlr-rust = "=0.3.0-beta"
better_any = "=0.2.0"
regex = "1"
yarn_slinger_core = { path = "../core" }
thiserror = "1"
strum = "0.25"
strum_macros = "0.25"
annotate-snippets = "0.10"
serde = { version = "1", features = ["derive"], optional = true }
bevy = { version = "0.12", default-features = false, optional = true }
rand = { version = "0.8", features = ["small_rng"] }
