[workspace]
resolver = "2"

members = [
    "crates/example_ui",
    "crates/bevy_plugin",
    "crates/yarn_slinger",
    "crates/runtime",
    "crates/compiler",
    "crates/core",
    "crates/macros",
    "crates/codegen",
    "demo",
    "examples/bevy_yarn_slinger",
]
