[package]
name = "yarn_slinger_runtime"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
yarn_slinger_core = { path = "../core" }
unicode-normalization = "0.1"
log = "0.4"
icu_plurals = { version = "1", features = ["std"] }
icu_locid = { version = "1", features = ["std"] }
icu_provider = { version = "1", features = ["std"] }
icu_provider_adapters = { version = "1", features = ["std"] }
fixed_decimal = { version = "0.5", features = ["ryu", "std"] }
zerovec =  { version = "0.9", features = ["std"] }
once_cell = "1"
regex = "1"

[build-dependencies]
icu_plurals = { version = "1", features = ["std"] }
icu_datagen = "1"
icu_provider_adapters = { version = "1", features = ["std"] }
