[package]
name = "yarn_slinger_runtime"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
yarn_slinger_core = { path = "../core" }
log = "0.4"
icu_plurals = "1.2"
icu_locid = "1.2"
icu_provider = "1.2"
icu_provider_adapters = "1.2"
fixed_decimal = { version = "0.5", features = ["ryu"] }
zerovec = "0.9"

[build-dependencies]
icu_plurals = "1.2"
icu_datagen = "1.2"
icu_provider_adapters = "1.2"
