[package]
name = "yarn_slinger"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
yarn_slinger_core = { path = "../core" }
yarn_slinger_compiler = { path = "../compiler" }
yarn_slinger_runtime = { path = "../runtime" }
log = "0.4"
