[package]
name = "yarn_slinger_examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bevy = "0.12"
bevy_yarn_slinger = { path = "../../crates/bevy_plugin" }
bevy_yarn_slinger_example_dialogue_view = { path = "../../crates/example_dialogue_view" }
