[package]
name = "yarnspinner_examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bevy = "0.12"
bevy_yarnspinner = { path = "../../crates/bevy_plugin" }
bevy_yarnspinner_example_dialogue_view = { path = "../../crates/example_dialogue_view" }
