[package]
name = "bevy_yarn_slinger"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
exclude = ["assets"]

[features]
default = []
serde = ["dep:serde", "yarn_slinger/serde", "bevy/serialize", "bitflags/serde"]

[dependencies]
anyhow = "1"
bitflags = "2"
yarn_slinger = { path = "../yarn_slinger", features = ["bevy"] }
serde = { version = "1", features = ["derive"] , optional = true }

[dependencies.bevy]
version = "0.10"
default-features = false
features = ["bevy_asset"]

