[package]
name = "bevy_yarn_slinger"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
exclude = ["assets", "wasm"]

[features]
default = []
audio_assets = ["bevy/bevy_audio", "bevy/vorbis"]

[dependencies]
anyhow = "1"
csv = "1"
seldom_fn_plugin = "0.5"
serde = { version = "1", features = ["derive"] }
yarn_slinger = { path = "../yarn_slinger", features = ["bevy", "serde"] }
sha2 = "0.10"
rand = { version = "0.8", features = ["small_rng"] }

[dependencies.bevy]
version = "0.12"
default-features = false
features = ["bevy_asset", "serialize", "multi-threaded"]

[dev-dependencies]
tempfile = "3"

[dev-dependencies.bevy]
version = "0.12"
default-features = false
features = [
  "bevy_core_pipeline",
  "bevy_render",
  "bevy_winit",
  "file_watcher",
  "x11",
  "bevy_audio",
]
