[package]
name = "bevy_yarn_slinger"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
exclude = ["assets"]

[features]
default = []

[dependencies]
anyhow = "1"
csv = "1"
seldom_fn_plugin = "0.3"
serde = { version = "1", features = ["derive"] }
yarn_slinger = { path = "../yarn_slinger", features = ["bevy", "serde"] }
sha2 = "0.10"

[dependencies.bevy]
version = "0.10"
default-features = false
features = ["bevy_asset", "serialize"]

[dev-dependencies]
tempfile = "3"
