[package]
name = "yarn_slinger_codegen"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = []
proto = ["dep:prost", "dep:prost-build"]
icu = ["dep:icu_plurals", "dep:icu_datagen", "dep:icu_provider_adapters"]

[[bin]]
name = "generate_proto"
required-features = ["proto"]


[[bin]]
name = "generate_icu"
required-features = ["icu"]

[dependencies]
prost = { version = "0.11", optional = true }
prost-build = { version = "0.11", optional = true }

icu_plurals = { version = "1", features = ["std"], optional = true }
icu_datagen = { version = "1", optional = true }
icu_provider_adapters = { version = "1", features = ["std"], optional = true }


