[package]
name = "bevy_yarnspinner_demo"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/YarnSpinnerTool/YarnSpinner-Rust"
homepage = "https://docs.yarnspinner.dev/"
keywords = ["gamedev", "dialog", "yarn", "bevy"]
categories = ["game-development", "compilers"]
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]

[features]
default = []
editor = ["dep:bevy_editor_pls"]

[dependencies]
bevy = "0.12"
bevy_yarnspinner = { path = "../crates/bevy_plugin", version = "0.1" }
bevy_yarnspinner_example_dialogue_view = { path = "../crates/example_dialogue_view", version = "0.1" }
bevy_sprite3d = "2.7"
bevy_editor_pls = { version = "0.7", optional = true }
