[package]
name = "rusty-yarn-spinner-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bytes = "1.4.0"
paste = "1.0.12"
prost = "0.11.9"
rusty-yarn-spinner-macros = { path = "../macros" }
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = "1.0.40"

[build-dependencies]
prost-build = "0.11.9"
