[package]
name = "yarn_slinger_core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bytes = "1"
paste = "1"
prost = "0.11"
yarn_slinger_macros = { path = "../macros" }
strum = "0.24.1"
strum_macros = "0.24"
thiserror = "1"

[build-dependencies]
prost-build = "0.11"
