[package]
name = "yarnspinner_core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = []
serde = ["dep:serde", "bevy?/serialize"]
bevy = ["dep:bevy"]

[dependencies]
bytes = "1"
paste = "1"
yarnspinner_macros = { path = "../macros" }
strum = "0.25"
strum_macros = "0.25"
thiserror = "1"
prost = "0.12"
serde = { version = "1", features = ["derive"], optional = true }
bevy = { version = "0.12", default-features = false, optional = true }
