[package]
name = "rusty-yarn-spinner"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
antlr-rust = { git = "https://github.com/rrevenantt/antlr4rust/", tag = "antlr4-4.8-2-Rust0.3.0-beta" }