[book]
authors = ["Jan Hohenheim"]
language = "en"
multilingual = false
src = "src"
title = "Yarn Spinner for Rust Book"

[output.html]
git-repository-url = "https://github.com/YarnSpinnerTool/YarnSpinner-Rust"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/YarnSpinnerTool/YarnSpinner-Rust/edit/main/docs/{path}"
site-url = "/YarnSpinner-Rust/"
cname = "https://yarnspinnertool.github.io"
