name: CI

on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  # Sparse cargo registry for faster updates
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  # Handle cargo check and cargo clippy warnings as errors
  RUSTFLAGS: "-D warnings"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1.0.0
      - name: Run cargo build (needed for build.rs to run)
        run: cargo build -p rusty-yarn-spinner-core
      - name: Run cargo clippy
        run: cargo clippy --workspace --all-features --tests --examples
      - name: Find generated files
        if: failure()
        run: find /home/runner/work/rusty-yarn-spinner/rusty-yarn-spinner/target/debug/build/*/**/Yarn.rs

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1.0.0
      - name: Run cargo fmt
        run: cargo fmt --check --all
      - name: Find generated files
        if: failure()
        run: find /home/runner/work/rusty-yarn-spinner/rusty-yarn-spinner/target/debug/build/*/**/Yarn.rs

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1.0.0
      - name: Run cargo build (needed for build.rs to run)
        run: cargo build -p rusty-yarn-spinner-core
      - name: Run cargo test
        run: cargo test --workspace --all-features
      - name: Find generated files
        if: failure()
        run: find /home/runner/work/rusty-yarn-spinner/rusty-yarn-spinner/target/debug/build/*/**/Yarn.rs
