name: CI

on:
  pull_request:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  # Sparse cargo registry for faster updates
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      # Handle cargo check and cargo clippy warnings as errors
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1.0.0
      - name: Run cargo clippy
        run: cargo clippy --workspace --all-features --tests --examples

  format:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1.0.0
      - name: Run cargo fmt
        run: cargo fmt --check --all

  check-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1.0.0
      - name: Run cargo check
        run: cargo check --workspace
      - name: Run cargo check for serde
        run: cargo check --workspace --features serde
      - name: Run cargo check for bevy
        run: cargo check --workspace --features bevy
      - name: Run cargo check for serde,bevy
        run: cargo check --workspace --features serde,bevy

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1.0.0
      - name: Run cargo test
        run: cargo test --workspace --all-features
